name: Deploy to Production Repo

on:
  push:
    branches:
      - main  # Solo cuando hay push a main en stockapp

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout stockapp (dev)
        uses: actions/checkout@v4

      - name: Clone revolucionmovil (prod)
        run: |
          git clone https://x-access-token:${{ secrets.PAT_PROD }}@github.com/julianzayas/revolucionmovil.git prod-repo

      - name: Copy files excluding configs
        run: |
          rsync -av --delete \
            --exclude 'config/database.php' \
            --exclude 'config/constantes.php' \
            --exclude 'includes/navbar.php' \
            --exclude 'login.php' \
            ./ prod-repo/

      - name: Commit and push changes to prod
        run: |
          cd prod-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from stockapp: $GITHUB_SHA" || echo "No changes to commit"
          git push origin main
